language: elixir
elixir:
  - 1.5.2
otp_release:
  - 20.1
before_script:
  - psql -U postgres -c "CREATE USER micro WITH PASSWORD 'pelkey.cRU28ul25!';"
  - psql -U postgres -c "CREATE DATABASE micro_test;"